### ISSUE TITLE
cannot configure package

### ISSUE THREAD

**Issue by emanjavacas** [LanguageMachines/ucto#45]
I am trying to install ucto from source but I am stuck with configure which keeps throwing:

```
checking that generated files are newer than configure... done
configure: error: conditional "OLD_LM" was never defined.
Usually this means the macro was only invoked conditionally.
```

I remember being able to compile it in the past, should I perhaps checkout a particular stable version?

**Comment by emanjavacas** [comment]
I found it out. It turns out I was missing libtextcat. Closing this issue.

**Comment by kosloot** [comment]
Yes, indeed.
Yesterday I checked in some code to stop the configure process if libtextcat is unavailable.
Instead of a lame attempt to build without.
Did you use the latest GIT head? That should have worked :{
Or, wild guess: did you just a ``git pull`` and then ``make`` ?
That might fail...
It is necessary to do a ``make distclean`` and then a complete ``bootstrap`` and ``configure  ``cycle.

**Comment by proycon** [comment]
(The git version has no configure yet, only the dist tarball does, bootstrapping the autoconf/automake is necessary anyway)
